/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flownex_libecono_SerialPort_FLOWCON */

#ifndef _Included_com_flownex_libecono_SerialPort_FLOWCON
#define _Included_com_flownex_libecono_SerialPort_FLOWCON
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
