/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flownex_libecono_SerialPort */

#ifndef _Included_com_flownex_libecono_SerialPort
#define _Included_com_flownex_libecono_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flownex_libecono_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;IIIIII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_flownex_libecono_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_flownex_libecono_SerialPort
 * Method:    serial_read
 * Signature: (Ljava/io/FileDescriptor;[BII)I
 */
JNIEXPORT jint JNICALL Java_com_flownex_libecono_SerialPort_serial_1read
   (JNIEnv *env, jobject thiz, jobject fd, jbyteArray buf , jint size , jint T);

/*
 * Class:     com_flownex_libecono_SerialPort
 * Method:    serial_write
 * Signature: (Ljava/io/FileDescriptor;[BI)I
 */
JNIEXPORT jint JNICALL Java_com_flownex_libecono_SerialPort_serial_1write
  (JNIEnv *env , jobject thiz, jobject fd , jbyteArray write_buffer, jint size);

/*
 * Class:     com_flownex_libecono_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flownex_libecono_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
